site_name: UPPMAX Documentation

repo_url: https://github.com/UPPMAX/UPPMAX-documentation

nav:
  - Home: index.md
  - Getting Started:
    - Get started: getting_started/get_started.md
    - Applying for a Project: getting_started/project_apply.md
    - Logging in:
      - Logging into Rackham: getting_started/login_rackham.md
      - Logging into Snowy: getting_started/login_snowy.md
      - Logging into Bianca: getting_started/login_bianca.md
    - Linux tutorials:
      - Working in Linux: getting_started/linux.md
      - Basic Linux commands: getting_started/linux_basics.md
  - Cluster user guide:
    - Modules: cluster_guides/modules.md
    - Slurm: cluster_guides/slurm.md
    - Running your first job: getting_started/first_job.md
    - Installing: cluster_guides/install.md
    - Own development:
      - Compiling serial code: cluster_guides/compiling_serial.md
      - Compiling parallel code: cluster_guides/compiling_parallel.md
  - Software:
    - Overview: software/overview.md
    - Software-specific documentation:
      - R: software/R.md
      - Python: software/python.md
      - Julia: software/julia.md
      - MATLAB: software/matlab.md
  - Databases: databases/overview.md
  - Workshops and courses: workshops_courses/workshops_courses.md
  - Support: support.md

theme:
  name: material
  greetings: Welcome to UPPMAX userguide
  font:
    text: Lato
    code: JetBrains Mono

  logo: assets/logo_color.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - search.suggest
    - content.code.annotate
    - content.tabs.link

  custom_dir: mkdocs_uppmax/
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
