site_name: UPPMAX Documentation

nav:
  - Intro: 
    - Landing : index.md
    - Demo : index.md
  - Getting Started:
    - Applying for a Project: getting_started/project_apply.md
    - Logging into Rackham: getting_started/login_rackham.md
    - Logging into Snowy: getting_started/login_snowy.md
    - Logging into Bianca: getting_started/login_bianca.md
    - Running your first job: getting_started/first_job.md
  - Hardware:
    - Rackham: hardware/system_rackham.md
    - Snowy: hardware/system_snowy.md
    - Bianca: hardware/system_bianca.md
  - Running Jobs:
    - Slurm: running_jobs/slurm.md
  - Software:
    - Overview: software/index.md

theme:
  name: material
  greetings: Welcome to UPPMAX userguide
  font:
    text: Lato

  #logo: assets/logo.png

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate

  custom_dir: mkdocs_uppmax/
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
