site_name: UPPMAX Documentation

repo_url: https://github.com/UPPMAX/UPPMAX-documentation

nav:
  - Home: index.md
  - Getting Started:
    - Applying for a Project: getting_started/project_apply.md
    - Logging into Rackham: getting_started/login_rackham.md
    - Logging into Snowy: getting_started/login_snowy.md
    - Logging into Bianca: getting_started/login_bianca.md
    - Running your first job: getting_started/first_job.md
  - Hardware:
    - Overview: hardware/overview.md
    - Clusters:
      - Rackham: hardware/clusters/rackham.md
      - Snowy: hardware/clusters/snowy.md
      - Bianca: hardware/clusters/bianca.md
    - Storage:
      - Crex: hardware/storage/crex.md
      - Domus: hardware/storage/domus.md
      - Castor: hardware/storage/castor.md
      - Lutra: hardware/storage/lutra.md
  - Running Jobs:
    - Slurm: running_jobs/slurm.md
  - Software:
    - Overview: software/overview.md
  - Support: support.md

theme:
  name: material
  greetings: Welcome to UPPMAX userguide
  font:
    text: Lato
    code: JetBrains Mono

  logo: assets/logo.svg

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
    - content.tabs.link

  custom_dir: mkdocs_uppmax/
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
