site_name: UPPMAX Documentation

repo_url: https://github.com/UPPMAX/UPPMAX-documentation
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Getting Started:
    - Get started: getting_started/get_started.md
    - Applying for a Project: getting_started/project_apply.md
    - Accessing UPPMAX:
      - Get inside the university networks: getting_started/get_inside_sunet.md
      - Log in to Pelle: getting_started/login_pelle.md
      - Log in to Bianca: getting_started/login_bianca.md
      - Log in to Rackham: getting_started/login_rackham.md
      - Log in to Snowy: getting_started/login_snowy.md
      - Log in to Dardel (at PDC): getting_started/login_dardel.md
    - Linux tutorials:
      - Working in Linux: getting_started/linux.md
      - Basic Linux commands: getting_started/linux_basics.md
#    - Running your first job: getting_started/first_job.md
  - Cluster user guide:
    - The UPPMAX clusters: cluster_guides/uppmax_cluster.md
    - System usage: cluster_guides/system_usage/system_usage.html
    - Clusters:
      - Pelle: cluster_guides/pelle.md
      - Rackham: cluster_guides/rackham.md
      - Bianca: cluster_guides/bianca.md
      - Snowy: cluster_guides/snowy.md
      - Dardel (at PDC): cluster_guides/dardel.md
    - Storage systems:
      - UPPMAX storage systems: cluster_guides/uppmax_storage_system.md
      - Object storage Spirula: cluster_guides/spirula.md
    - General cluster tools: 
      - Start an interactive session: cluster_guides/start_interactive_session.md
      - Modules: cluster_guides/modules.md
      - Slurm: cluster_guides/slurm.md
      - Managing your project: cluster_guides/project_management.md
    - Running jobs:
      - Checking and optimizing jobs: cluster_guides/optimizing_jobs.md
      - Runtime tips: cluster_guides/runtime_tips.md
      - Storage and compression: cluster_guides/storage_compression.md
      - Screen: software/screen.md
    - Data transfer: 
      - Transfer to/from Pelle: cluster_guides/transfer_pelle.md
      - Transfer to/from Rackham: cluster_guides/transfer_rackham.md
      - Transfer to/from Bianca: cluster_guides/transfer_bianca.md
      - Webexport: cluster_guides/webexport.md
  - Software:
    - Overview: software/overview.md
    - Software table: software/software-table.md
    - Text editors: software/text_editors.md
    - Software-specific documentation:      
      - Chemistry/physics/atmosphere:
        - GAMESS_US: software/games_us.md
        - Gaussian: software/gaussian.md
        - GROMACS: software/gromacs.md
        - WRF: software/wrf.md
      - Integrated development environments (IDE):
        - Jupyter: software/jupyter.md
        - RStudio: software/rstudio.md
        - VSCode: software/vscode.md
        - VSCodium: software/vscodium.md
      - Life Science: 
        - BEAST: software/beast.md
        - BEAST2: software/beast2.md
        - Cram: software/cram.md
        - IGV: software/igv.md
        - MetONTIIME: software/metontiime.md
        - Tracer: software/tracer.md
      - Machine Learning and AI:
        - NVIDIA DLF: software/nvidia-deep-learning-frameworks.md
        - TensorFlow: software/tensorflow.md
        - Whisper: software/whisper.md
      - Programming languages:
        - Julia: software/julia.md
        - MATLAB: software/matlab.md
        - Python: software/python.md
        - Perl: software/perl.md
        - R: software/r.md
      - Misc tools:
        - Allinea DDT: software/allinea-ddt.md
        - darsync: software/darsync.md
        - jobstats: software/jobstats.md
        - projplot: software/projplot.md
        - Rclone: software/rclone.md      
        - SSH: software/ssh.md
        - SFTP: software/sftp.md
        - ThinLinc: software/thinlinc.md
    - Installing and development: 
      - Installing: software/install.md
      - Installing with conda: software/conda.md
      - Compilers: software/compilers.md
      - Compiling serial code: software/compiling_serial.md
      - Compiling parallel code: software/compiling_parallel.md
      - Debuggers: software/debuggers.md
      - Nextflow & nf-core: software/nextflow.md   
      - Profilers: software/profilers.md
      - Singularity/Apptainer: software/singularity.md
      - Spack: software/spack.md
      
  - Databases: 
      - Overview: databases/overview.md
      - BLAST databases available locally: databases/blast.md
      - NCBI taxonomy databases: databases/ncbi.md
      - DIAMOND protein alignment databases: databases/diamond.md
      - Reference genomes: databases/reference_genomes.md
      - 1000-genome project: databases/1000-genome_project.md
      - Simons Genome Diversity Project datasets: databases/simons_genome.md
      - Other bioinformatics-oriented local data resources: databases/other_local.md
     
  - Support: support.md

  - Courses and workshops: 
      - Overview: courses_workshops/courses_workshops.md
      - AWK: courses_workshops/awk.md
      - Bianca intro: courses_workshops/bianca_intro.md
      - Bianca intermediate: courses_workshops/bianca_intermediate.md
      - File transfer: courses_workshops/naiss_transfer.md
      - HPC Python: courses_workshops/hpc_python.md
      - Intro to Python: courses_workshops/intro_to_python.md
      - Programming formalisms: courses_workshops/programming_formalisms.md
      - R-MATLAB-Julia: courses_workshops/R_matlab_julia.md
      - Singularity: courses_workshops/singularity.md
      - UPPMAX intro: courses_workshops/uppmax_intro_course.md

  - UPPMAX main page: https://www.uu.se/en/centre/uppmax


not_in_nav: |
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  backup.md
  contributors.md
  glossary.md
  cluster_guides/arrhenius.md
  cluster_guides/backup.md
  cluster_guides/bianca_fingerprints.md
  cluster_guides/bianca_login_node.md
  cluster_guides/bianca_modules.md
  cluster_guides/bianca_overview.md
  cluster_guides/biancas_design.md
  cluster_guides/biancas_name.md
  cluster_guides/cluster_guide_faq.md
  cluster_guides/cluster_speeds.md
  cluster_guides/compress_fastQ.md
  cluster_guides/compress_format.md
  cluster_guides/compress_guide.md
  cluster_guides/crex.md
  cluster_guides/cygnus.md
  cluster_guides/dardel_migration.md
  cluster_guides/disk_quota_more.md
  cluster_guides/disk_storage_guide.md
  cluster_guides/extend_duration_of_running_job.md
  cluster_guides/file_transfer.md
  cluster_guides/files.md
  cluster_guides/get_data_from_an_expired_project.md
  cluster_guides/grace_period.md
  cluster_guides/interactive_more.md
  cluster_guides/login_node.md
  cluster_guides/login_node_restrictions.md
  cluster_guides/login_transit.md
  cluster_guides/maja.md
  cluster_guides/miarka.md
  cluster_guides/module_conflicts.md
  cluster_guides/mount_wharf.md
  cluster_guides/nodes_own_disk.md
  cluster_guides/pelle_file_transfer_using_gui.md
  cluster_guides/pelle_file_transfer_using_transit.md
  cluster_guides/pelle_fingerprints.md
  cluster_guides/pelle_modules.md
  cluster_guides/pelle_test.md
  cluster_guides/pelles_name.md
  cluster_guides/rackham4.md
  cluster_guides/rackham_file_transfer_using_gui.md
  cluster_guides/rackham_file_transfer_using_transit.md
  cluster_guides/rackham_fingerprints.md
  cluster_guides/rackham_modules.md
  cluster_guides/rackhams_design.md
  cluster_guides/rackhams_name.md
  cluster_guides/slurm_details.md
  cluster_guides/slurm_on_bianca.md
  cluster_guides/slurm_on_bianca_details.md
  cluster_guides/slurm_on_pelle.md
  cluster_guides/slurm_on_rackham.md
  cluster_guides/slurm_on_snowy.md
  cluster_guides/slurm_scheduler.md
  cluster_guides/slurm_troubleshooting.md
  cluster_guides/snapshot.md
  cluster_guides/snowys_design.md
  cluster_guides/snowys_name.md
  cluster_guides/software_on_transit.md
  cluster_guides/start_interactive_session_on_bianca.md
  cluster_guides/start_interactive_session_on_pelle.md
  cluster_guides/start_interactive_session_on_rackham.md
  cluster_guides/start_interactive_session_on_snowy.md
  cluster_guides/system_status.md
  cluster_guides/transfer_dardel.md
  cluster_guides/transfer_transit.md
  cluster_guides/transit.md
  cluster_guides/transit_file_transfer_using_gui.md
  cluster_guides/uppmax.md
  cluster_guides/uppmax_as_an_organization.md
  cluster_guides/uppmax_cloud.md
  cluster_guides/uppmax_filesystem.md
  cluster_guides/uppmax_history.md
  cluster_guides/uppmax_systems.md
  cluster_guides/wharf.md
  cluster_guides/wharf2.md
  cluster_guides/to_add_to_doc/README.md
  databases/swegen.md
  getting_started/bianca_usage_prerequisites.md
  getting_started/change_uppmax_password.md
  getting_started/first_job.md
  getting_started/get_uppmax_2fa.md
  getting_started/get_uppmax_2fa_qr.md
  getting_started/get_uppmax_2fa_qr_code.md
  getting_started/join_existing_project.md
  getting_started/login.md
  getting_started/login_bianca_console_password.md
  getting_started/login_bianca_console_password_no_sunet.md
  getting_started/login_bianca_console_ssh_key.md
  getting_started/login_bianca_console_ssh_key_no_sunet.md
  getting_started/login_bianca_remote_desktop_local_thinlinc_client.md
  getting_started/login_bianca_remote_desktop_website.md
  getting_started/login_bianca_remote_desktop_website_no_sunet.md
  getting_started/login_pelle_console_password.md
  getting_started/login_pelle_console_ssh_key.md
  getting_started/login_pelle_remote_desktop_local_thinlinc_client.md
  getting_started/login_pelle_remote_desktop_website.md
  getting_started/login_rackham_console_password.md
  getting_started/login_rackham_console_ssh_key.md
  getting_started/login_rackham_remote_desktop_local_thinlinc_client.md
  getting_started/login_rackham_remote_desktop_website.md
  getting_started/pelle_usage_prerequisites.md
  getting_started/project.md
  getting_started/project_apply_bianca.md
  getting_started/project_apply_pelle.md
  getting_started/project_apply_scc.md
  getting_started/project_apply_simpler.md
  getting_started/rackham_usage_prerequisites.md
  getting_started/reset_uppmax_password.md
  getting_started/setup_vpn.md
  getting_started/setup_vpn_uu_linux.md
  getting_started/snowy_usage_prerequisites.md
  getting_started/storage.md
  getting_started/supr.md
  getting_started/supr_register.md
  getting_started/user_account.md
  getting_started/why_2fa.md
  hardware/overview.md
  hardware/clusters/bianca.md
  hardware/clusters/decomissioned_clusters.md
  hardware/clusters/miarka.md
  hardware/clusters/pelle.md
  hardware/clusters/rackham.md
  hardware/clusters/snowy.md
  hardware/clusters/uppmax_cloud.md
  hardware/storage/castor.md
  hardware/storage/crex.md
  hardware/storage/cygnus.md
  hardware/storage/decomissioned_storage_systems.md
  hardware/storage/domus.md
  hardware/storage/gorilla.md
  hardware/storage/lutra.md
  hardware/storage/spirula.md
  hardware/storage/vulpes.md
  naiss/README.md
  naiss/alvis.md
  naiss/alvis_file_transfer_using_filezilla.md
  naiss/alvis_file_transfer_using_rsync.md
  naiss/arrhenius.md
  naiss/cosmos.md
  naiss/cosmos_file_transfer_using_filezilla.md
  naiss/cosmos_file_transfer_using_rsync.md
  naiss/cosmos_file_transfer_using_scp.md
  naiss/dardel.md
  naiss/dardel_file_transfer_using_filezilla.md
  naiss/dardel_file_transfer_using_rsync.md
  naiss/file_transfer_using_filezilla.md
  naiss/file_transfer_using_rsync.md
  naiss/hpc2n.md
  naiss/kebnekaise.md
  naiss/login.md
  naiss/login_alvis.md
  naiss/login_cosmos.md
  naiss/login_kebnekaise.md
  naiss/lumi_file_transfer_using_filezilla.md
  naiss/lumi_file_transfer_using_rsync.md
  naiss/lunarc.md
  naiss/request_tracker.md
  naiss/rstudio_on_alvis.md
  naiss/rstudio_on_berzelius.md
  naiss/rstudio_on_cosmos.md
  naiss/rstudio_on_dardel.md
  naiss/rstudio_on_kebnekaise.md
  naiss/rstudio_on_lumi.md
  naiss/rstudio_on_tetralith.md
  naiss/rstudio_on_vera.md
  naiss/ssh_key_use_tetralith.md
  naiss/swestore.md
  naiss/tetralith.md
  naiss/tetralith_file_transfer_using_rsync.md
  software/bash.md
  software/bianca_file_transfer_using_filezilla.md
  software/bianca_file_transfer_using_gui.md
  software/bianca_file_transfer_using_lftp.md
  software/bianca_file_transfer_using_rsync.md
  software/bianca_file_transfer_using_sftp.md
  software/bianca_file_transfer_using_winscp.md
  software/cellranger.md
  software/chmod.md
  software/containers.md
  software/cowsay.md
  software/create_singularity_container.md
  software/create_singularity_container_for_r_package.md
  software/create_singularity_container_from_a_singularity_script.md
  software/create_singularity_container_from_a_singularity_script_on_linux.md
  software/create_singularity_container_from_a_singularity_script_using_remote_builder.md
  software/create_singularity_container_from_a_singularity_script_using_remote_builder_from_rackham.md
  software/create_singularity_container_from_conda.md
  software/create_singularity_container_from_docker_pull.md
  software/create_singularity_container_from_dockerhub.md
  software/dnabert2.md
  software/doc.md
  software/emacs.md
  software/eog.md
  software/filezilla.md
  software/finishedjobinfo.md
  software/gcc.md
  software/gcc_compile_c.md
  software/gcc_compile_cpp.md
  software/gcc_compile_fortran.md
  software/gdb.md
  software/gedit.md
  software/git_on_bianca.md
  software/globus.md
  software/gprof.md
  software/icc.md
  software/icc_compile_c.md
  software/icpc.md
  software/icpc_compile_cpp.md
  software/icx.md
  software/icx_compile_c.md
  software/idb.md
  software/ides.md
  software/ides_on_bianca.md
  software/ides_on_pelle.md
  software/ides_on_rackham.md
  software/ifort.md
  software/ifort_compile_fortran.md
  software/ifx.md
  software/ifx_compile_fortran.md
  software/intel_advisor.md
  software/intel_vtune.md
  software/interactive.md
  software/ipython.md
  software/javac.md
  software/javac_compile_java.md
  software/jobinfo.md
  software/julia_pelle.md
  software/jupyter_local.md
  software/jupyter_on_bianca.md
  software/jupyter_on_rackham.md
  software/jvarkit.md
  software/matlab_addons.md
  software/matlab_conf.md
  software/matlab_ide_on_pelle.md
  software/matlab_local.md
  software/mobaxterm.md
  software/multiqc.md
  software/nano.md
  software/nedit.md
  software/openmolcas.md
  software/orthofinder.md
  software/parallel_comb.md
  software/pelle_file_transfer_using_filezilla.md
  software/pelle_file_transfer_using_rsync.md
  software/pelle_file_transfer_using_scp.md
  software/pelle_file_transfer_using_sftp.md
  software/pelle_file_transfer_using_transit_scp.md
  software/pelle_file_transfer_using_transit_scp_from_pelle.md
  software/pelle_file_transfer_using_transit_scp_from_transit.md
  software/pelle_file_transfer_using_transit_sftp.md
  software/pelle_file_transfer_using_transit_sftp_from_pelle.md
  software/pelle_file_transfer_using_transit_sftp_from_transit.md
  software/pelle_file_transfer_using_winscp.md
  software/perl_packages.md
  software/picard.md
  software/pixi.md
  software/projinfo.md
  software/puttygen.md
  software/python_install_packages.md
  software/python_parallel_jobs.md
  software/python_pelle.md
  software/python_programming.md
  software/python_pyenv.md
  software/python_venv.md
  software/python_virtual_environments.md
  software/python_virtualenv.md
  software/pytorch.md
  software/qiime2.md
  software/r_packages_bianca.md
  software/r_packages_bianca2.md
  software/rackham_file_transfer_using_filezilla.md
  software/rackham_file_transfer_using_rsync.md
  software/rackham_file_transfer_using_scp.md
  software/rackham_file_transfer_using_sftp.md
  software/rackham_file_transfer_using_transit_scp.md
  software/rackham_file_transfer_using_transit_scp_from_rackham.md
  software/rackham_file_transfer_using_transit_scp_from_transit.md
  software/rackham_file_transfer_using_transit_sftp.md
  software/rackham_file_transfer_using_transit_sftp_from_rackham.md
  software/rackham_file_transfer_using_transit_sftp_from_transit.md
  software/rackham_file_transfer_using_winscp.md
  software/rstudio_on_bianca.md
  software/rstudio_on_pelle.md
  software/rstudio_on_rackham.md
  software/rsync.md
  software/rsync_on_bianca.md
  software/rsync_on_rackham.md
  software/sbatch.md
  software/scancel.md
  software/scp.md
  software/seff.md
  software/sinfo.md
  software/squeue.md
  software/ssh_client.md
  software/ssh_key_use.md
  software/ssh_key_use_bianca.md
  software/ssh_key_use_dardel.md
  software/ssh_key_use_pelle.md
  software/ssh_key_use_rackham.md
  software/ssh_x_forwarding.md
  software/tabix.md
  software/terminal.md
  software/test.md
  software/thinlinc_error_no_server_agent_was_available.md
  software/thinlinc_on_bianca.md
  software/thinlinc_on_rackham.md
  software/tkinter.md
  software/transit_file_transfer_using_filezilla.md
  software/transit_file_transfer_using_scp.md
  software/transit_file_transfer_using_sftp.md
  software/transit_file_transfer_using_winscp.md
  software/uquota.md
  software/valgrind.md
  software/vartrix.md
  software/venv_on_rackham.md
  software/vim.md
  software/vscode_on_bianca.md
  software/vscode_on_rackham.md
  software/vscodium_on_bianca.md
  software/vscodium_on_rackham.md
  software/winscp.md
  software/xclock.md
  software/xeyes.md
  staff/README.md
  staff/sysadmin_responsibility.md
  staff/uppmax_matrix.md
  storage/compress_fastQ.md
  storage/compress_format.md
  storage/compress_guide.md
  storage/disk_storage_guide.md
  uppmax/gitlab.md

theme:
  name: material
  greetings: Welcome to UPPMAX userguide
  font:
    text: Lato
    code: JetBrains Mono

  logo: assets/logo_color.png
  # logo_dark_mode: assets/UU_logo_vit.svg
  # logo_light_mode: assets/logo_color.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    # - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
#    - navigation.expand
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.copy


  custom_dir: mkdocs_uppmax/
    
#extra:
#  homepage: https://www.uu.se/en/centre/uppmax
  
extra_css:
  - stylesheets/extra.css
      
extra_javascript:
  - js/kapa-widget.js

markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde 
  - md_in_html

plugins:
  - search
  - open-in-new-tab 
  - mkdocs-video:
      video_muted: True
      video_autoplay: True
      video_loop: True
      video_controls: False
