site_name: UPPMAX Documentation

repo_url: https://github.com/UPPMAX/UPPMAX-documentation

nav:
  - Home: index.md
  - Getting Started:
    - Get started: getting_started/get_started.md
    - Applying for a Project: getting_started/project_apply.md
    - Logging in:
      - Get inside the university networks: getting_started/get_inside_sunet.md
      - Logging into Bianca: getting_started/login_bianca.md
      - Logging into Dardel: getting_started/login_dardel.md
      - Logging into Rackham: getting_started/login_rackham.md
      - Logging into Snowy: getting_started/login_snowy.md
    - Linux tutorials:
      - Working in Linux: getting_started/linux.md
      - Basic Linux commands: getting_started/linux_basics.md
#    - Running your first job: getting_started/first_job.md
  - Cluster user guide:
    - The UPPMAX clusters: cluster_guides/uppmax_cluster.md
    - Cluster portals: 
      - Bianca portal: cluster_guides/bianca_portal.md
      - Dardel portal: cluster_guides/dardel_portal.md
      - Rackham portal: cluster_guides/rackham_portal.md
      - Snowy portal: cluster_guides/snowy_portal.md
    - General cluster tools: 
      - Modules: cluster_guides/modules.md
      - Slurm: cluster_guides/slurm.md
      - Optimizing jobs: cluster_guides/optimizing_jobs.md
    - Data transfer: 
      - Transfer to/from Bianca: cluster_guides/transfer_bianca.md
      - Migrate to Dardel: cluster_guides/dardel_migration.md
      - Transfer to/from Rackham: cluster_guides/transfer_rackham.md
    - Installing and development: 
      - Installing: cluster_guides/install.md
      - Installing with conda: cluster_guides/conda.md
      - Compiling serial code: cluster_guides/compiling_serial.md
      - Compiling parallel code: cluster_guides/compiling_parallel.md
  - Software:
    - Overview: software/overview.md
    - Text editors: software/text_editors.md
    - Software-specific documentation:
      - BEAST: software/beast.md
      - BEAST2: software/beast2.md
      - Darsync: cluster_guides/darsync.md
      - GROMACS: software/gromacs.md
      - Julia: software/julia.md
      - MATLAB: software/matlab.md
      - Perl: software/perl.md
      - Python: software/python.md
      - R: software/r.md
      - RStudio: software/rstudio.md
      - SSH: software/ssh.md
      - Tracer: software/tracer.md
      - Whisper: software/whisper.md
      - Life Science-specific: 
        - Cram: software/cram.md
        - IGV: software/igv.md
  - Databases: 
     - Overview: databases/overview.md
     - BLAST databases available locally: databases/blast.md
     - NCBI taxonomy databases: databases/ncbi.md
     - DIAMOND protein alignment databases: databases/diamond.md
     - Reference genomes: databases/reference_genomes.md
     - 1000-genome project: databases/1000-genome_project.md
     - Simons Genome Diversity Project datasets: databases/simons_genome.md
     - Other bioinformatics-oriented local data resources: databases/other_local.md
     
#  - Workshops and courses: workshops_courses/workshops_courses.md
  - Support: support.md

theme:
  name: material
  greetings: Welcome to UPPMAX userguide
  font:
    text: Lato
    code: JetBrains Mono

  logo: assets/logo_color.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  custom_dir: mkdocs_uppmax/
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
