site_name: Userguide

nav:
  - Intro: 
    - Welcome: index.md
  - Software:
    - Overview: software/index.md

theme:
  name: material
  greetings: Welcome to UPPMAX userguide

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate

    #custom_dir: mkdocs_uppmax/
    #
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
